import './material.css'
import 'regenerator-runtime/runtime'

// WebComponents
// import '@webcomponents/webcomponentsjs/webcomponents-loader'
import '@webcomponents/webcomponentsjs/webcomponents-bundle'
import '@webcomponents/webcomponentsjs/custom-elements-es5-adapter'

// Material Web Components
import '@material/mwc-button/mwc-button'
import '@material/mwc-switch/mwc-switch'
import '@material/mwc-checkbox/mwc-checkbox'
import '@material/mwc-icon/mwc-icon'
import '@authentic/mwc-menu/mwc-menu'
import '@authentic/mwc-list/mwc-list-item'
import '@material/chips/mdc-chips'
// Paper (Polymer) Components
import '@polymer/paper-input/paper-input'
import '@polymer/iron-icon/iron-icon'
import '@polymer/iron-icons/iron-icons'
import '@polymer/iron-icons/av-icons'
import '@polymer/iron-icons/image-icons'
import '@polymer/iron-icons/editor-icons'
import '@polymer/paper-icon-button/paper-icon-button'
import '@polymer/paper-tabs/paper-tabs'
import '@polymer/paper-tabs/paper-tab'
import '@polymer/paper-progress/paper-progress'
import '@polymer/paper-spinner/paper-spinner-lite'
import '@polymer/paper-fab/paper-fab'
import '@polymer/paper-dialog/paper-dialog'
